---
app_path: /srv
traefik_network: traefik_net
domain: ad2ien.dev
org_name: ad2ien

nextcloud_sub_domain: nextcloud
wireguard_sub_domain: wireguard
messaging_sub_domain: im
element_sub_domain: element
registry_sub_domain: registry
registry_ui_sub_domain: registry-ui

frps_port: 7007
frps_tcpmux_port: 5007
vhost_frps_port: 7080
frps_webserver_port: 7507
frps_monitor: frp
